"""addition header column to posts

Revision ID: 45de7b49711c
Revises: 74d5ddb8bbcd
Create Date: 2025-06-12 08:30:15.244599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45de7b49711c'
down_revision = '74d5ddb8bbcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('header', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('header')

    # ### end Alembic commands ###
