"""addition category_name, url, keywords to posts

Revision ID: 74d5ddb8bbcd
Revises: cdae10bc2bc6
Create Date: 2025-06-11 13:51:27.522479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74d5ddb8bbcd'
down_revision = 'cdae10bc2bc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('category_name', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('keywords', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('keywords')
        batch_op.drop_column('category_name')
        batch_op.drop_column('url')

    # ### end Alembic commands ###
