"""addition restrict, priority and grant status fields to posts and users

Revision ID: cdae10bc2bc6
Revises: b2393fcad010
Create Date: 2025-06-10 14:06:47.245081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdae10bc2bc6'
down_revision = 'b2393fcad010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restrict_status', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('priority_status', sa.SmallInteger(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grant_status', sa.SmallInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('grant_status')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('priority_status')
        batch_op.drop_column('restrict_status')

    # ### end Alembic commands ###
